name: flutter_pagination_search_filter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  bloc_concurrency: ^0.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  graphql: ^5.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  bloc_test: ^8.2.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.4
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
